package flugsuche.servlet;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import flugsuche.bean.Buchung;
import flugsuche.bean.Buchungsposition;
import flugsuche.bean.Zusatzleistung;

/**
 * Servlet implementation class ZahlungSpeichern
 */
@WebServlet("/ZahlungSpeichern")
public class ZahlungSpeichern extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Resource(lookup = "jdbc/__default")
	private DataSource ds;
	private Connection connection;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public ZahlungSpeichern() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		HttpSession session = request.getSession();
		try {
			connection = ds.getConnection();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		Buchung buchung = (Buchung) session.getAttribute("Buchung");

	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

	private void insertBuchung(Buchung buchung) {

		String sql = "INSERT INTO (zeitstempel,fk_kunde,Zahlungsart,Zahlungsnummer)  buchung VALUES(?,?,?,?,?)";

		try {
			PreparedStatement preparedStatement = connection.prepareStatement(sql);
			preparedStatement.setInt(1, buchung.getId());
			preparedStatement.setDate(2, new Date(System.currentTimeMillis()));
			preparedStatement.setInt(3, buchung.getId());
			preparedStatement.setString(4, buchung.getZahlungsart());
			preparedStatement.setString(5, buchung.getZahlungsnummer());

			preparedStatement.executeQuery();

			ResultSet result = preparedStatement.executeQuery();

			result.next();
			int autoGeneratedID = result.getInt(1);

			buchung.setId(autoGeneratedID);

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void insertBuchungsposition(Buchung buchung) {

		List<Buchungsposition> positionen = buchung.getPositionen();

		for (Buchungsposition pos : positionen) {
		
			String sql = "INSERT INTO buchungsposition (buchungsid, fk_flug, fk_zusatzleistung, passagierVorname, passagierNachname, geburtsdatum, preis) VALUES(?,?,?,?,?,?,?,?,?,?)";

			try {
				PreparedStatement preparedStatement = connection.prepareStatement(sql);
				preparedStatement.setInt(1, pos.getBuchung().getId());
				preparedStatement.setInt(2, pos.getFlug().getId());
				preparedStatement.setInt(3, pos.getZusatzleistung().getId());
				preparedStatement.setString(4, pos.getPassagierVorname());
				preparedStatement.setString(5, pos.getPassagierNachname());
				preparedStatement.setDate(6, new Date(pos.getGeburtsdatum().getTime()));
				preparedStatement.setDouble(7, pos.getPreis());
				
				preparedStatement.executeQuery();

				ResultSet result = preparedStatement.executeQuery();


			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

}
